post_install() {
  echo ""
  echo ">>> Font, colour and your preferred terminal application for dmenu"
  echo "    can be set in ~/.dmenurc"
  echo ""
}

post_upgrade() {
  echo ""
  echo ">>> dmenu can be configured in your ~/.dmenurc file."
  echo "    To change your preferred terminal command edit or add the variable 'TERMINAL_CMD'"
  echo "    for example: TERMINAL_CMD=\"lxterminal -e\""
  echo ""
}
